name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta al hacer push en la rama "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Descarga el código fuente del repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Configura Node.js versión 16

    - name: Install dependencies
      run: npm install  # Instala las dependencias de tu proyecto

    - name: Build project
      env:  # Aquí se usan los secretos
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        echo "Clave API: $API_KEY"
        echo "Base URL: $BASE_URL"
        npm run build  # Compila tu proyecto usando las variables de entorno

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Carpeta que contiene los archivos compilados
